version: '3'
services:
  nodered:
    container_name: doreme_nodered
    restart: always
    image: nodered/node-red
    user: '0'    
    ports:
      - '1880:1880'
    volumes:
      - ./nodered:/data
    links:
      - mongo
      - broker
  mongo:
    container_name: doreme_mongo
    restart: always
    environment:
      - MONGODB_AUTH=false
#Switch below depending on running on a Linux (mongo:latest) or RasPi (webhippie/mongodb
    image: webhippie/mongodb
#    image: mongo:latest
    user: '0'
    volumes:
      - ./mongo:/var/lib/mongodb
    ports:
      - '27017:27017'
  broker:
    container_name: doreme_broker
    restart: always
    image: eclipse-mosquitto
    user: '0'    
    ports:
      - '1883:1883'
      - '1884:1884'
    volumes:
      - ./mosquitto:/mosquitto
volumes:
  certs:

