version: '3'
services:
  nodered:
    container_name: nodered
    restart: always
    image: nodered/node-red-docker
    user: '0'
    ports:
      - '80:1880'
      - '443:1880'
    volumes:
      - ./nodered:/data
      - ./certs:/certs      
    links:
      - mongo
      - broker
  mongo:
    container_name: mongo
    restart: always
#    user: '0'
    environment:
      - MONGODB_AUTH=false
    image: mongo
    volumes:
      - ./db:/data/db
#    ports:
#      - '27017:27017'
  broker:
    container_name: broker
    restart: always
    image: eclipse-mosquitto
    user: '0'
    ports:
      - '1883:1883'
      - '1884:1884'
      - '8883:8883'
    volumes:
      - ./mosquitto:/mosquitto
      - ./certs:/certs
volumes:
  certs:
  local:
